name: CI for Dockerfile and HTML/JavaScript

on:
  push:
    branches:
      - trunck
  pull_request:
    branches:
      - trunck

jobs:
  lint-html:
    name: Validate HTML and JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTML and JavaScript linters
        run: |
          npm install -g htmlhint eslint

      - name: Lint HTML
        run: |
          htmlhint index.html
        env:
          HTMLHINT_RC: |
            {
              "attr-lowercase": true,
              "tag-pair": true,
              "doctype-first": true,
              "id-unique": true,
              "src-not-empty": true
            }

      - name: Lint embedded JavaScript in HTML
        run: |
          eslint index.html --ext .html

  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Hadolint
        run: |
          curl -sL https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Run Hadolint
        run: |
          hadolint Dockerfile

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-docker-image:latest .

