name: CI for HTML and Docker

on:
  push:
    branches:
      - trunck 
  pull_request:
    branches:
      - trunck

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTML Validator
        run: |
          npm install -g html-validator-cli

      - name: Validate HTML
        run: |
          html-validator --file=index.html --verbose

  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2
        with:
          file: Dockerfile

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-image:latest .

