name: CI for Dockerfile

on:
  push:
    branches:
      - trunck  # Exécuter uniquement sur la branche `trunck`

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2: Installer Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Étape 3: Construire l'image Docker
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Étape 4: Vérifier que l'image Docker fonctionne (simuler le test sans exécuter)
      - name: Test Docker image (Simuler push vers DockerHub)
        run: |
          echo "Simulating the push of the Docker image to DockerHub"
          # Cette étape est une simulation, aucune image n'est réellement envoyée.
          echo "Image would be pushed to DockerHub: myapp:latest"

      # Étape 5: Nettoyer (facultatif)
      - name: Clean up
        run: docker system prune -f
