name: CI for Dockerfile with Playwright Tests

on:
  push:
    branches:
      - trunck  # Exécuter uniquement sur la branche `trunck`

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Installer Node.js et Playwright
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
          npx playwright install
          npx playwright install-deps

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Lancer le conteneur
      - name: Run Docker container
        run: |
          docker run -d --name myapp-container -p 8080:80 myapp:latest
          sleep 5  # Attendre que le conteneur soit prêt

      # Exécuter les tests Playwright
      - name: Run Playwright tests
        run: |
          npx playwright test tests/formInteraction.test.js

      # Arrêter le conteneur après les tests
      - name: Stop Docker container
        run: |
          docker stop myapp-container
          docker rm myapp-container

      # Nettoyer les ressources Docker
      - name: Clean up
        run: docker system prune -f
