name: CI Workflow

on:
  push:
    branches:
      - trunck # Ta branche avec une faute, mais ça fonctionne 😉
  pull_request:
    branches:
      - trunck

jobs:
  lint:
    name: Lint HTML and JS
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Version LTS recommandée de Node.js

      # Étape 3 : Installer les dépendances (ESLint et plugins)
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécuter ESLint sur index.html
      - name: Run ESLint
        run: npm run lint

  docker-build:
    name: Build and Test Dockerfile
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Construire l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t my-app:test .

      # Étape 3 : Tester l'image Docker
      - name: Run Docker container
        run: |
          docker run --rm my-app:test
