name: CI for My Website

on:
  push:
    branches:
      - trunck    # Exécuter sur la branche principale
  pull_request:
    branches:
      - trunck    # Exécuter sur les PR vers main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Version de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint  # Commande pour vérifier le style de code

      - name: Run Tests
        run: npm test  # Commande pour exécuter les tests

      - name: Build Project
        run: npm run build  # Commande pour compiler ton site, si nécessaire

